### ISSUE TITLE
Integration with Ionic

### ISSUE THREAD

**Issue by musakacmaz** [simplewebrtc/SimpleWebRTC#669]
hello everyone, i'm trying to develop a mobile application by using ionic framework which includes peer-to-peer video chat. i can set up communication when running the app on browser. but when deploy it to a real device there is nothing on the screen.  how can i achieve this problem? thanks in advance.

**Comment by mortenbirkelund** [comment]
I think you will have to provide a bit more detail as to what is wrong. 
Any errors in the console?
Have you setup a Turn server?

**Comment by blow09** [comment]
no, i don't get any error there is just blank screen and i didn't setup my own server i'm using default SimpleWebRTC server.

**Comment by mortenbirkelund** [comment]
The default SimpleWebRTC signal server doesn't include A Turn server, and should not be used in production.
Read up on why a turn server can be nessesary for successfully establishing connections

**Comment by sergei202** [comment]
@blow09: Check for any errors:
```
this.webRTC.on('localMediaError', err => {
	console.error('localMediaError: '+ err);
});
```

I had a lot of trouble building for Ionic because WebRTC needs to run from a secure host (at least on Android).  So everything works great on localhost, but fails running on an actual device.

I finally got it working by using the [crosswalk plugin](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview).
